### ISSUE TITLE
Make GitHub issues data dictate in which frame node is placed

### ISSUE THREAD

**Issue by qubist** [h-be/translator#19]

**Comment by samcooley** [comment]
My understanding from standup on 2019-06-03 that this would be nice but not prioritized

**Comment by qubist** [comment]
GitHub issue data should be repo

**Comment by qubist** [comment]
@samcooley It seems important and shouldn't take too long. I'm going to do it.

**Comment by samcooley** [comment]
cool, then am I to understand this would use the labels as well as repo for frame placement? I agree it feels important, but thought I heard some logic from @zippy that it was not necessary
(presuming you have already done it, pretty sure we can drop discussion)
