### ISSUE TITLE
When adding new items into tree, font size should scale.

### ISSUE THREAD

**Issue by zippy** [h-be/translator#35]
Currently the size of the item scales according to the size of the frame, but the font size remains at 14, which looks really funny when the item pops into a large frame.

**Comment by qubist** [comment]
<img width="1259" alt="Screen Shot 2019-06-17 at 9 59 56 AM" src="https://user-images.githubusercontent.com/3607279/59616684-edf12500-90f2-11e9-90aa-1f9599914b8f.png">
